name: Jest Testing Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: yarn
      env:
        ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        ACCOUNT_ACTIVATION_TOKEN_EXPIRES_IN: ${{ secrets.ACCOUNT_ACTIVATION_TOKEN_EXPIRES_IN }}
        ACCOUNT_ACTIVATION_TOKEN_SECRET: ${{ secrets.ACCOUNT_ACTIVATION_TOKEN_SECRET }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
        BLOB_URL: ${{ secrets.BLOB_URL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PASSWORD_RESET_TOKEN_EXPIRES_IN: ${{ secrets.PASSWORD_RESET_TOKEN_EXPIRES_IN }}
        PASSWORD_RESET_TOKEN_SECRET: ${{ secrets.PASSWORD_RESET_TOKEN_SECRET }}
        PORT: ${{ secrets.PORT }}
        REFRESH_TOKEN_EXPIRES_IN: ${{ secrets.REFRESH_TOKEN_EXPIRES_IN }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
    - run: yarn test
