name: Jest Testing Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: yarn
    - name: Create .env file
      run: |
        echo "ACCESS_TOKEN_EXPIRES_IN=${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}" >> .env
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
        echo "ACCOUNT_ACTIVATION_TOKEN_EXPIRES_IN=${{ secrets.ACCOUNT_ACTIVATION_TOKEN_EXPIRES_IN }}" >> .env
        echo "ACCOUNT_ACTIVATION_TOKEN_SECRET=${{ secrets.ACCOUNT_ACTIVATION_TOKEN_SECRET }}" >> .env
        echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> .env
        echo "BLOB_CONTAINER_NAME=${{ secrets.BLOB_CONTAINER_NAME }}" >> .env
        echo "BLOB_URL=${{ secrets.BLOB_URL }}" >> .env
        echo "EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }}" >> .env
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
        echo "MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
        echo "PASSWORD_RESET_TOKEN_EXPIRES_IN=${{ secrets.PASSWORD_RESET_TOKEN_EXPIRES_IN }}" >> .env  
        echo "PASSWORD_RESET_TOKEN_SECRET=${{ secrets.PASSWORD_RESET_TOKEN_SECRET }}" >> .env  
        echo "PORT=${{ secrets.PORT }}" >> .env  
        echo "REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN }}" >> .env  
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env  
    - run: yarn test
